#!/usr/bin/python3
import sys

def factorize(n):
    f = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            f.append(i)
    return f

def main(file_name):
    with open(file_name, 'r') as file:
        for line in file:
            n = int(line.strip())
            f = factorize(n)
            if f:
                p, q = f[0], n // f[0]
                print(f"{n}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    file_name = sys.argv[1]
    main(file_name)
